alertmanager:
  enabled: false
nodeExporter:
  enabled: false
grafana:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
