# 1. Khai báo kho chứa (Trỏ về AWS bằng Access Key)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: smartshop
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret-creds
            key: secret-access-key
---
# 2. Yêu cầu kéo mật khẩu về
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-external
  namespace: smartshop
spec:
  refreshInterval: 1m 
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials 
    creationPolicy: Owner
  data:
  - secretKey: postgres-password 
    remoteRef:
      key: smartshop/db-credentials 
      property: postgres-password 